### PR TITLE
fix(ui): Netlify deployment error

### PR DESCRIPTION
**Pull request by kennethjor**
```
Nov 7, 10:12:56 AM: ace746b7 ERROR  [nuxt] [request error] [unhandled] [500] Cannot find module '@vue/devtools-api'
Require stack:
- /var/task/server.mjs
Nov 7, 10:12:56 AM: ace746b7 ERROR  [nuxt] [request error] [unhandled] [500] _createApp is not a function
```

image

Found this forum post https://answers.netlify.com/t/functions-cannot-find-module-vue-devtools-api/129081 which implies install `@vue/devtools-api` explicitly can fix it. That was not the case for me.

### CODE REVIEW

**Comment by kennethjor** [comment]
It looks like it was broken by https://github.com/autonomouslogic/eve-ref/pull/680

**Comment by kennethjor** [comment]
Moved the site to Cloudflare Pages instead https://github.com/autonomouslogic/eve-ref/pull/684
